

N, L = map(int, input().split())

apple_flavors = [L + i for i in range(N)]  # list of apple flavors

apple_flavors.remove(max(apple_flavors))  # remove the apple with the worst flavor



# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
# I'm a comment
print(sum(apple_flavors))
