

#!/usr/bin/env python3

import sys
import math
import random
import os
import time
import re
import string
import operator
import collections
import heapq
import collections
import bisect
import functools
import numpy as np
import copy
import itertools
import queue
import array
import scipy.misc
import networkx as nx
import threading
import sys
import datetime
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
import bisect
import functools
import heapq
import itertools
import operator
import copy
import string
import queue
import array
import scipy.misc
import networkx as nx
import threading
import random
import re
import os
import sys
import math
import time
import collections
