

def get_digit(k):
    """
    Returns the digit at position k in the sequence
    """
    if k == 1:
        return 1
    # Get the number of digits in the number that k corresponds to
    # This is the number of digits in the block that k is in
    num_digits = 1
    while 10**num_digits < k:
        num_digits += 1
    # Get the index of the number that k corresponds to
    # This is the index of the number in the block that k is in
    num_index = (k - 10**(num_digits - 1)) // num_digits
    # Get the number that k corresponds to
    # This is the number in the block that k is in
    num = 10**(num_digits - 1) + num_index
    # Get the index of the digit that k corresponds to
    # This is the index of the digit in the number that k is in
    digit_index = (k - 10**(num_digits - 1)) % num_digits
    # Get the digit that k corresponds to
    # This is the digit in the number that k is in
    digit = int(str(num)[digit_index])
    return digit

# q = int(input())
# for i in range(q):
#     k = int(input())
#     print(get_digit(k))

print(get_digit(1))
print(get_digit(2))
print(get_digit(3))
print(get_digit(4))
print(get_digit(5))
print(get_digit(6))
print(get_digit(7))
print(get_digit(8))
print(get_digit(9))
print(get_digit(10))
print(get_digit(11))
print(get_digit(12))
print(get_digit(13))
print(get_digit(14))
print(get_digit(15))
print(get_digit(16))
print(get_digit(17))
print(get_digit(18))
print(get_digit(19))
print(get_digit(20))
print(get_digit(21))
print(get_digit(22))
print(get_digit(23))
print(get_digit(24))
print(get_digit(25))
print(get_digit(26))
print(get_digit(27))
print(get_digit(28))
print(get_digit(29))
print(get_digit(30))
print(get_digit(31))
print(get_digit(32))
print(get_digit(33))
print(get_digit(34))
print(get_digit(35))
print(get_digit(36))
print(get_digit(37))
print(get_digit(38))
print(get_digit(39))
print(get_digit(40))
print(get_digit(41))
print(get_digit(42))
print(get_digit(43))
print(get_digit(44))
print(get_digit(45))
print(get_digit(46))
print(get_digit(47))
print(get_digit(48))
print(get_digit(49))
print(get_digit(50))
print(get_digit(51))
print(get_digit(52))
print(get_digit(53))
print(get_digit(54))
print(get_digit(55))
print(get_digit(56))
print(get_digit(57))
print(get_digit(58))
print(get_digit(59))
print(get_digit(60))
print(get_digit(61))
print(get_digit(62))
print(get_digit(63))
print(get_digit(64))
print(get_digit(65))
print(get_digit(66))
print(get_digit(67))
print(get_digit(68))
print(get_digit(69))
print(get_digit(70))
print(get_digit(71))
print(get_digit(72))
print(get_digit(73))
print(get_digit(74))
print(get_digit(75))
print(get_digit(76))
print(get_digit(77))
print(get_digit(78))
print(get_digit(79))
print(get_digit(80))
print(get_digit(81))
print(get_digit(82))
print(get_digit(83))
print(get_digit(84))
print(get_digit(85))
print(get_digit(86))
print(get_digit(87))
print(get_digit(88))
print(get_digit(89))
print(get_digit(90))
print(get_digit(91))
print(get_digit(92))
print(get_digit(93))
print(get_digit(94))
print(get_digit(95))
print(get_digit(96))
print(get_digit(97))
print(get_digit(98))
print(get_digit(99))
print(get_digit(100))
print(get_digit(101))
print(get_digit(102))
print(get_digit(103))
print(get_digit(104))
print(get_digit(105))
print(get_digit(106))
print(get_digit(107))
print(get_digit(108))
print(get_digit(109))
print(get_digit(110))
print(get_digit(111))
print(get_digit(112))
print(get_digit(113))
print(get_digit(114))
print(get_digit(115))
print(get_digit(116))
print(get_digit(117))
print(get_digit(118))
print(get_digit(119))
print(get_digit(120))
print(get_digit(121))
print(get_digit(122))
print(get_digit(123))
print(get_digit(124))
print(get_digit(125))
print(get_digit(126))
print(get_digit(127))
print(get_digit(128))
print(get_digit(129))
print(get_digit(130))
print(get_digit(131))
print(get_digit(132))
print(get_digit(133))
print(get_digit(134))
print(get_digit(135))
print(get_digit(136))
print(get_digit(137))
print(get_digit(138))
print(get_digit(139))
print(get_digit(140))
print(get_digit(141))
print(get_digit(142))
print(get_digit(143))
print(get_digit(144))
print(get_digit(145))
print(get_digit(146))
print(get_digit(147))
print(get_digit(148))
print(get_digit(149))
print(get_digit(150))
print(get_digit(151))
print(get_digit(152))
print(get_digit(153))
print(get_digit(154))
print(get_digit(155))
print(get_digit(156))
print(get_digit(157))
print(get_digit(158))
print(get_digit(159))
print(get_digit(160))
print(get_digit(161))
print(get_digit(162))
print(get_digit(163))
print(get_digit(164))
print(get_digit(165))
print(get_digit(166))
print(get_digit(167))
print(get_digit(168))
print(get_digit(169))
print(get_digit(170))
print(get_digit(171))
print(get_digit(172))
print(get_digit(173))
print(get_digit(174))
print(get_digit(175))
print(get_digit(176))
print(get_digit(177))
print(get_digit(178))
print(get_digit(179))
print(get_digit(180))
print(get_digit(181))
print(get_digit(182))
print(get_digit(183))
print(get_digit(184))
print(get_digit(185))
print(get_digit(186))
print(get_digit(187))
print(get_digit(188))
print(get_digit(189))
print(get_digit(190))
print(get_digit(191))
print(get_digit(192))
print(get_digit(193))
print(get_digit(194))
print(get_digit(195))
print(get_digit(196
