import os
import sys
import subprocess

def main():
    #n = int(sys.stdin.readline())
    #correct_answers = 0
    #for i in range(n):
    #    answer = sys.stdin.readline()
    #    if answer == "A\n":
    #        correct_answers += 1
    #print(correct_answers)
    #os.system("ls")
    #subprocess.call(["ls", "-l"])
    #subprocess.call(["ls", "-l", "/etc/passwd"])
    #subprocess.call(["echo", "hello world"])
    #subprocess.call(["echo", "hello", "world"])
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)
    #subprocess.call(["echo", "hello", "world"], shell=True)

if __name__ == "__main__":
    main()
