

# x = int(input())
# year = 0
# balance = 100
# while balance < x:
#     balance += balance // 100
#     year += 1
# print(year)

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a * b + c * d)

# a = int(input())
# b = int(input())
# c = int(input())
# print(a * b * c)
# print(2 * a * b + 2 * b * c + 2 * a * c)

# a = int(input())
# b = int(input())
# print(a // b)
# print(a % b)
# print(divmod(a, b))

# a = int(input())
# b = int(input())
# print(a // b)
# print(a % b)
# print(divmod(a, b))

# a = int(input())
# b = int(input())
# print(a // b)
# print(a % b)
# print(divmod(a, b))

# a = int(input())
# b = int(input())
# print(a // b)
# print(a % b)
# print(divmod(a, b))

# a = int(input())
# b = int(input())
# print(a // b)
# print(a % b)
# print(divmod(a, b))

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a, b)[0], divmod(a, b)[1], divmod(a, b), divmod(c, d)[0], divmod(c, d)[1], divmod(c, d), sep='\n')

# a = int(input())
# b = int(input())
# c = int(input())
# d = int(input())
# print(a // b, a % b, divmod(a, b), sep='\n')
# print(c // d, c % d, divmod(c, d), sep='\n')
# print(divmod(a,
