# GitLab

## Introduction

GitLab is the leading integrated product for modern software development. Connecting issue management, version control, code review, CI, CD, and monitoring into a single, easy-to-install application, we help teams go faster from planning to monitoring. GitLab provides a single data store, one user interface, and one permission model across the DevOps lifecycle allowing teams to collaborate, significantly reducing cycle time and focus exclusively on building great software quickly.

## About this Chart

This chart bootstraps a [GitLab](https://gitlab.com) installation on a [Kubernetes](http://kubernetes.io) cluster using the [Helm](https://helm.sh) package manager.

## Prerequisites

- Kubernetes 1.6+ with Beta APIs enabled
- PV provisioner support in the underlying infrastructure

## Installing the Chart

To install the chart with the release name `my-release`:

```console
$ helm install --name my-release stable/gitlab
```

The command deploys GitLab on the Kubernetes cluster in the default configuration. The [configuration](#configuration) section lists the parameters that can be configured during installation.

> **Tip**: List all releases using `helm list`

## Uninstalling the Chart

To uninstall/delete the `my-release` deployment:

```console
$ helm delete my-release
```

The command removes all the Kubernetes components associated with the chart and deletes the release.

## Configuration

The following table lists the configurable parameters of the GitLab chart and their default values.

| Parameter                                          | Description                                                                                                                                                                                                                                                        | Default                                                                                                                                                          |
| -------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `externalUrl`                                      | The GitLab URL.                                                                                                                                                                                                                                                    | `http://gitlab.example.com`                                                                                                                                        |
| `image.registry`                                   | The GitLab image registry.                                                                                                                                                                                                                                         | `registry.gitlab.com`                                                                                                                                              |
| `image.repository`                                 | The GitLab image repository.                                                                                                                                                                                                                                       | `gitlab/gitlab-ce`                                                                                                                                                  |
| `image.tag`                                        | The GitLab image tag.                                                                                                                                                                                                                                             | `9.4.4-ce.0`                                                                                                                                                        |
| `image.pullPolicy`                                 | The GitLab image pull policy.                                                                                                                                                                                                                                     | `IfNotPresent`                                                                                                                                                     |
| `image.pullSecrets`                                | The GitLab image pull secrets.                                                                                                                                                                                                                                    | `[]`                                                                                                                                                               |
| `gitlab.host`                                      | The GitLab host (without http/https).                                                                                                                                                                                                                             | `gitlab.example.com`                                                                                                                                                |
| `gitlab.nginx.ssl.enabled`                         | Enable SSL for the GitLab web interface.                                                                                                                                                                                                                          | `false`                                                                                                                                                            |
| `gitlab.nginx.ssl.certificate`                     | SSL certificate for the GitLab web interface.                                                                                                                                                                                                                     | `gitlab.example.com.crt`                                                                                                                                           |
| `gitlab.nginx.ssl.certificateKey`                  | SSL certificate key for the GitLab web interface.                                                                                                                                                                                                                 | `gitlab.example.com.key`                                                                                                                                           |
| `gitlab.sidekiq.resources.requests.cpu`            | The CPU resource requests for the Sidekiq process.                                                                                                                                                                                                                | `100m`                                                                                                                                                             |
| `gitlab.sidekiq.resources.limits.cpu`              | The CPU resource limits for the Sidekiq process.                                                                                                                                                                                                                  | `500m`                                                                                                                                                             |
| `gitlab.sidekiq.resources.requests.memory`         | The memory resource requests for the Sidekiq process.                                                                                                                                                                                                             | `256Mi`                                                                                                                                                            |
| `gitlab.sidekiq.resources.limits.memory`           | The memory resource limits for the Sidekiq process.                                                                                                                                                                                                               | `512Mi`                                                                                                                                                            |
| `gitlab.unicorn.resources.requests.cpu`            | The CPU resource requests for the Unicorn process.                                                                                                                                                                                                                | `100m`                                                                                                                                                             |
| `gitlab.unicorn.resources.limits.cpu`              | The CPU resource limits for the Unicorn process.                                                                                                                                                                                                                  | `500m`                                                                                                                                                             |
| `gitlab.unicorn.resources.requests.memory`         | The memory resource requests for the Unicorn process.                                                                                                                                                                                                             | `256Mi`                                                                                                                                                            |
| `gitlab.unicorn.resources.limits.memory`           | The memory resource limits for the Unicorn process.                                                                                                                                                                                                               | `512Mi`                                                                                                                                                            |
| `gitlab.unicorn.workerProcesses`                   | The number of Unicorn worker processes.                                                                                                                                                                                                                          | `2`                                                                                                                                                                |
| `gitlab.minio.enabled`                             | Enable the Minio object storage server.                                                                                                                                                                                                                           | `false`                                                                                                                                                            |
| `gitlab.minio.accessKey`                           | The Minio access key.                                                                                                                                                                                                                                             | `minio`                                                                                                                                                            |
| `gitlab.minio.secretKey`                           | The Minio secret key.                                                                                                                                                                                                                                             | `minio123`                                                                                                                                                         |
| `gitlab.minio.resources.requests.cpu`              | The CPU resource requests for the Minio process.                                                                                                                                                                                                                  | `100m`                                                                                                                                                             |
| `gitlab.minio.resources.limits.cpu`                | The CPU resource limits for the Minio process.                                                                                                                                                                                                                    | `500m`                                                                                                                                                             |
| `gitlab.minio.resources.requests.memory`           | The memory resource requests for the Minio process.                                                                                                                                                                                                               | `256Mi`                                                                                                                                                            |
| `gitlab.minio.resources.limits.memory`             | The memory resource limits for the Minio process.                                                                                                                                                                                                                 | `512Mi`                                                                                                                                                            |
| `gitlab.redis.persistence.enabled`                 | Enable a persistent Redis volume.                                                                                                                                                                                                                                 | `true`                                                                                                                                                             |
| `gitlab.redis.persistence.size`                    | The Redis persistent volume size.                                                                                                                                                                                                                                | `8Gi`                                                                                                                                                              |
| `gitlab.redis.resources.requests.cpu`              | The CPU resource requests for the Redis process.                                                                                                                                                                                                                  | `100m`                                                                                                                                                             |
