# coding: utf-8

import sys

def main():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))
    B = list(map(int, input().split()))
    C = list(map(int, input().split()))
    D = list(map(int, input().split()))
    E = list(map(int, input().split()))
    F = list(map(int, input().split()))
    G = list(map(int, input().split()))
    H = list(map(int, input().split()))
    I = list(map(int, input().split()))
    J = list(map(int, input().split()))
    K = list(map(int, input().split()))
    L = list(map(int, input().split()))
    M = list(map(int, input().split()))
    N = list(map(int, input().split()))
    O = list(map(int, input().split()))
    P = list(map(int, input().split()))
    Q = list(map(int, input().split()))
    R = list(map(int, input().split()))
    S = list(map(int, input().split()))
    T = list(map(int, input().split()))
    U = list(map(int, input().split()))
    V = list(map(int, input().split()))
    W = list(map(int, input().split()))
    X = list(map(int, input().split()))
    Y = list(map(int, input().split()))
    Z = list(map(int, input().split()))
    a = list(map(int, input().split()))
    b = list(map(int, input().split()))
    c = list(map(int, input().split()))
    d = list(map(int, input().split()))
    e = list(map(int, input().split()))
    f = list(map(int, input().split()))
    g = list(map(int, input().split()))
    h = list(map(int, input().split()))
    i = list(map(int, input().split()))
    j = list(map(int, input().split()))
    k = list(map(int, input().split()))
    l = list(map(int, input().split()))
    m = list(map(int, input().split()))
    n = list(map(int, input().split()))
    o = list(map(int, input().split()))
    p = list(map(int, input().split()))
    q = list(map(int, input().split()))
    r = list(map(int, input().split()))
    s = list(map(int, input().split()))
    t = list(map(int, input().split()))
    u = list(map(int, input().split()))
    v = list(map(int, input().split()))
    w = list(map(int, input().split()))
    x = list(map(int, input().split()))
    y = list(map(int, input().split()))
    z = list(map(int, input().split()))
    print(A)
    print(B)
    print(C)
    print(D)
    print(E)
    print(F)
    print(G)
    print(H)
    print(I)
    print(J)
    print(K)
    print(L)
    print(M)
    print(N)
    print(O)
    print(P)
    print(Q)
    print(R)
    print(S)
    print(T)
    print(U)
    print(V)
    print(W)
    print(X)
    print(Y)
    print(Z)
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)
    print(f)
    print(g)
    print(h)
    print(i)
    print(j)
    print(k)
    print(l)
    print(m)
    print(n)
    print(o)
    print(p)
    print(q)
    print(r)
    print(s)
    print(t)
    print(u)
    print(v)
    print(w)
    print(x)
    print(y)
    print(z)

if __name__ == '__main__':
    main()
