


def read_file(filename):
    with open(filename, "r", encoding="utf-8") as f:
        return f.read()


def write_file(filename, contents):
    with open(filename, "w", encoding="utf-8") as f:
        f.write(contents)


def main():
    filename = input("ファイル名を入力してください:")
    contents = read_file(filename)
    print(contents)

    contents = contents.replace("\n", "")
    contents = contents.replace(".", "")
    contents = contents.replace(",", "")
    contents = contents.replace("\"", "")
    contents = contents.replace("”", "")
    contents = contents.replace("'", "")
    contents = contents.replace("’", "")
    contents = contents.replace("[", "")
    contents = contents.replace("]", "")
    contents = contents.replace("(", "")
    contents = contents.replace(")", "")
    contents = contents.replace("{", "")
    contents = contents.replace("}", "")
    contents = contents.replace("（", "")
    contents = contents.replace("）", "")
    contents = contents.replace("《", "")
    contents = contents.replace("》", "")
    contents = contents.replace("［", "")
    contents = contents.replace("］", "")
    contents = contents.replace("【", "")
    contents = contents.replace("】", "")
    contents = contents.replace("！", "")
    contents = contents.replace("？", "")
    contents = contents.replace("：", "")
    contents = contents.replace("；", "")
    contents = contents.replace("…", "")
    contents = contents.replace("・", "")
    contents = contents.replace("／", "")
    contents = contents.replace("＼", "")
    contents = contents.replace("＿", "")
    contents = contents.replace("－", "")
    contents = contents.replace("＝", "")
    contents = contents.replace("＋", "")
    contents = contents.replace("＊", "")
    contents = contents.replace("＆", "")
    contents = contents.replace("＃", "")
    contents = contents.replace("％", "")
    contents = contents.replace("＄", "")
    contents = contents.replace("＠", "")
    contents = contents.replace("！", "")
    contents = contents.replace("？", "")
    contents = contents.replace("：", "")
    contents = contents.replace("；", "")
    contents = contents.replace("…", "")
    contents = contents.replace("・", "")
    contents = contents.replace("／", "")
    contents = contents.replace("＼", "")
    contents = contents.replace("＿", "")
    contents = contents.replace("－", "")
    contents = contents.replace("＝", "")
    contents = contents.replace("＋", "")
    contents = contents.replace("＊", "")
    contents = contents.replace("＆", "")
    contents = contents.replace("＃", "")
    contents = contents.replace("％", "")
    contents = contents.replace("＄", "")
    contents = contents.replace("＠", "")
    contents = contents.replace("０", "")
    contents = contents.replace("１", "")
    contents = contents.replace("２", "")
    contents = contents.replace("３", "")
    contents = contents.replace("４", "")
    contents = contents.replace("５", "")
    contents = contents.replace("６", "")
    contents = contents.replace("７", "")
    contents = contents.replace("８", "")
    contents = contents.replace("９", "")
    contents = contents.replace("Ａ", "")
    contents = contents.replace("Ｂ", "")
    contents = contents.replace("Ｃ", "")
    contents = contents.replace("Ｄ", "")
    contents = contents.replace("Ｅ", "")
    contents = contents.replace("Ｆ", "")
    contents = contents.replace("Ｇ", "")
    contents = contents.replace("Ｈ", "")
    contents = contents.replace("Ｉ", "")
    contents = contents.replace("Ｊ", "")
    contents = contents.replace("Ｋ", "")
    contents = contents.replace("Ｌ", "")
    contents = contents.replace("Ｍ", "")
    contents = contents.replace("Ｎ", "")
    contents = contents.replace("Ｏ", "")
    contents = contents.replace("Ｐ", "")
    contents = contents.replace("Ｑ", "")
    contents = contents.replace("Ｒ", "")
    contents = contents.replace("Ｓ", "")
    contents = contents.replace("Ｔ", "")
    contents = contents.replace("Ｕ", "")
    contents = contents.replace("Ｖ", "")
    contents = contents.replace("Ｗ", "")
    contents = contents.replace("Ｘ", "")
    contents = contents.replace("Ｙ", "")
    contents = contents.replace("Ｚ", "")
    contents = contents.replace("ａ", "")
    contents = contents.replace("ｂ", "")
    contents = contents.replace("ｃ", "")
    contents = contents.replace("ｄ", "")
    contents = contents.replace("ｅ", "")
    contents = contents.replace("ｆ", "")
    contents = contents.replace("ｇ", "")
    contents = contents.replace("ｈ", "")
    contents = contents.replace("ｉ", "")
    contents = contents.replace("ｊ", "")
    contents = contents.replace("ｋ", "")
    contents = contents.replace("ｌ", "")
    contents = contents.replace("ｍ", "")
    contents = contents.replace("ｎ", "")
    contents = contents.replace("ｏ", "")
    contents = contents.replace("ｐ", "")
    contents = contents.replace("ｑ", "")
    contents = contents.replace("ｒ", "")
    contents = contents.replace("ｓ", "")
    contents = contents.replace("ｔ", "")
    contents = contents.replace("ｕ", "")
    contents = contents.replace("ｖ", "")
    contents = contents.replace("ｗ", "")
    contents = contents.replace("ｘ", "")
    contents = contents.replace("ｙ", "")
    contents = contents.replace("ｚ", "")

    write_file("output.txt", contents)


if __name__ == "__main__":
    main()

n = int(input())
s = input()

max_count = 0
max_two_gram = ""

for i in range(n-1):
    two_gram = s[i:i+2]
    count = s.count(two_gram)
    if count > max_count:
        max_count = count
        max_two_gram = two_gram

print(max_two_gram)
