import os

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")

# os.mkdir("new_dir")
# os.chdir("new_dir")
# os.getcwd()
# os.chdir("..")
# os.rmdir("new_dir")
