

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
n,m=map(int,input().split())
a=list(map(int,input().split()))
b=list(map(int,input().split()))
c=list(map(int,input().split()))
d=list(map(int,input().split()))
e=list(map(int,input().split()))
f=list(map(int,input().split()))
g=list(map(int,input().split()))
h=list(map(int,input().split()))
i=list(map(int,input().split()))
j=list(map(int,input().split()))
k=list(map(int,input().split()))
l=list(map(int,input().split()))
m=list(map(int,input().split()))
o=list(map(int,input().split()))
p=list(map(int,input().split()))
q=list(map(int,input().split()))
r=list(map(int,input().split()))
s=list(map(int,input().split()))
t=list(map(int,input().split()))
u=list(map(int,input().split()))
v=list(map(int,input().split()))
w=list(map(int,input().split()))
x=list(map(int,input().split()))
y=list(map(int,input().split()))
z=list(map(int,input().split()))
