
# -*- coding: utf-8 -*-
import sys
import os
import re
import math
import datetime
import collections
import itertools
import bisect
import heapq
import queue
import random
import string
import copy
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
import networkx as nx
import pandas as pd
import json
import pickle
import time
import copy
import functools
import operator
import csv
import io
import struct
import shutil
import zipfile
import zlib
import hashlib
import inspect
import contextlib
import threading
import multiprocessing
import traceback
import sys
import warnings
import typing
import weakref
import dataclasses
import typing
import contextlib
import numbers
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
import contextlib
import dataclasses
import inspect
import io
import contextlib
import pathlib
import functools
import operator
import itertools
import collections
import heapq
import queue
import bisect
import random
import math
import cmath
import decimal
import fractions
import typing
import typing_extensions
import typing_inspect
