
a = input('Name of file: ')
b = input('Name of file: ')
c = input('Name of file: ')
d = input('Name of file: ')
e = input('Name of file: ')
f = input('Name of file: ')
g = input('Name of file: ')
h = input('Name of file: ')
i = input('Name of file: ')
j = input('Name of file: ')
k = input('Name of file: ')
l = input('Name of file: ')
m = input('Name of file: ')
n = input('Name of file: ')
o = input('Name of file: ')
p = input('Name of file: ')
q = input('Name of file: ')
r = input('Name of file: ')
s = input('Name of file: ')
t = input('Name of file: ')
u = input('Name of file: ')
v = input('Name of file: ')
w = input('Name of file: ')
x = input('Name of file: ')
y = input('Name of file: ')
z = input('Name of file: ')
print('{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n{}\n'.format(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z))
