import sys
import heapq
from collections import deque
from collections import defaultdict
from collections import Counter
from collections import OrderedDict
from collections import namedtuple
from collections import deque
from collections import abc
from collections import Iterable
from collections import Iterator
from collections import Sequence
from collections import Sized
from collections import Container
from collections import Callable
from collections import Hashable
from collections import Mapping
from collections import MappingView
from collections import MutableMapping
from collections import MutableSequence
from collections import MutableSet
from collections import ItemsView
from collections import KeysView
from collections import ValuesView
from collections import deque
from collections import ChainMap
from collections import Counter
from collections import OrderedDict
from collections import defaultdict
from collections import UserDict
from collections import UserList
from collections import UserString
from collections import _Link
from collections import _ChainMap
from collections import _count_elements
from collections import _heapq
from collections import _OrderedDict
from collections import _deque
from collections import _eq
from collections import _iskeyword
from collections import _itemgetter
from collections import _proxy
from collections import _recursive_repr
from collections import _repeat
from collections import _starmap
from collections import _sys
from collections import _tee
from collections import _unique_everseen
from collections import _repeat
from collections import _starmap
from collections import _tee
from collections import _unique_everseen
from collections import _OrderedDict
from collections import _count_elements
from collections import _heapq
from collections import _Link
from collections import _ChainMap
from collections import _eq
from collections import _iskeyword
from collections import _itemgetter
from collections import _proxy
from collections import _recursive_repr
from collections import _sys
from collections import abc
from collections import namedtuple
from collections import defaultdict
from collections import OrderedDict
from collections import Counter
from collections import ChainMap
from collections import UserDict
from collections import UserList
from collections import UserString
from collections import deque
from collections import Mapping
from collections import MutableMapping
from collections import MappingView
from collections import ItemsView
from collections import KeysView
from collections import ValuesView
from collections import MutableSequence
from collections import MutableSet
from collections import Callable
from collections import Container
from collections import Hashable
from collections import Iterable
from collections import Iterator
from collections import Sized
from collections import Sequence
from collections import Set
from collections import Mapping
from collections import MappingView
from collections import ItemsView
from collections import KeysView
from collections import ValuesView
from collections import MutableMapping
from collections import MutableSequence
from collections import MutableSet
from collections import Callable
from collections import Container
from collections import Hashable
from collections import Iterable
from collections import Iterator
from collections import Sized
from collections import Sequence
from collections import Set
from collections import Mapping
from collections import MappingView
from collections import ItemsView
from collections import KeysView
from collections import ValuesView
from collections import MutableMapping
from collections import MutableSequence
from collections import MutableSet
from collections import Callable
from collections import Container
from collections import Hashable
from collections import Iterable
from collections import Iterator
from collections import Sized
from collections import Sequence
from collections import Set
from collections import Mapping
from collections import MappingView
from collections import ItemsView
from collections import KeysView
from collections import ValuesView
from collections import MutableMapping
from collections import MutableSequence
from collections import MutableSet
from collections import Callable
from collections import Container
from collections import Hashable
from collections import Iterable
from collections import Iterator
from collections import Sized
from collections import Sequence
from collections import Set

class Solution:
    def canThreePartsEqualSum(self, A) -> bool:
        total = sum(A)
        if total % 3 != 0:
            return False
        target = total // 3
        cur = 0
        count = 0
        for num in A:
            cur += num
            if cur == target:
                count += 1
                cur = 0
        return count == 3
