

# a, b = map(int, input().split())
# print(a + b)

# a = int(input())
# b = int(input())
# print(a + b)

# a = int(input())
# b = int(input())
# print(a - b)

# a = int(input())
# b = int(input())
# print(a * b)

# a = int(input())
# b = int(input())
# print(a // b)

# a = int(input())
# b = int(input())
# print(a % b)

# a = int(input())
# b = int(input())
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)

# a = int(input())
# b = int(input())
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)
# print(a ** b)

# a = int(input())
# b = int(input())
# print(
