

# SOLUTION

n, k = map(int, input().split())
s = input()
for i in range(k): 
    s = s.replace('a','',1)
    s = s.replace('b','',1)
    s = s.replace('c','',1)
    s = s.replace('d','',1)
    s = s.replace('e','',1)
    s = s.replace('f','',1)
    s = s.replace('g','',1)
    s = s.replace('h','',1)
    s = s.replace('i','',1)
    s = s.replace('j','',1)
    s = s.replace('k','',1)
    s = s.replace('l','',1)
    s = s.replace('m','',1)
    s = s.replace('n','',1)
    s = s.replace('o','',1)
    s = s.replace('p','',1)
    s = s.replace('q','',1)
    s = s.replace('r','',1)
    s = s.replace('s','',1)
    s = s.replace('t','',1)
    s = s.replace('u','',1)
    s = s.replace('v','',1)
    s = s.replace('w','',1)
    s = s.replace('x','',1)
    s = s.replace('y','',1)
    s = s.replace('z','',1)
print(s)
