#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_LINE_LENGTH 200
#define MAX_LINES_NUMBER 100

int main() {
    FILE *fp;
    char line[MAX_LINE_LENGTH];
    char *lines[MAX_LINES_NUMBER];
    int i = 0;
    int j = 0;
    int k = 0;
    int l = 0;
    int m = 0;
    int n = 0;
    int linesNumber = 0;
    char *p;
    char *p1;
    char *p2;
    char *p3;
    char *p4;
    char *p5;
    char *p6;
    char *p7;
    char *p8;
    char *p9;
    char *p10;
    char *p11;
    char *p12;
    char *p13;
    char *p14;
    char *p15;
    char *p16;
    char *p17;
    char *p18;
    char *p19;
    char *p20;
    char *p21;
    char *p22;
    char *p23;
    char *p24;
    char *p25;
    char *p26;
    char *p27;
    char *p28;
    char *p29;
    char *p30;
    char *p31;
    char *p32;
    char *p33;
    char *p34;
    char *p35;
    char *p36;
    char *p37;
    char *p38;
    char *p39;
    char *p40;
    char *p41;
    char *p42;
    char *p43;
    char *p44;
    char *p45;
    char *p46;
    char *p47;
    char *p48;
    char *p49;
    char *p50;
    char *p51;
    char *p52;
    char *p53;
    char *p54;
    char *p55;
    char *p56;
    char *p57;
    char *p58;
    char *p59;
    char *p60;
    char *p61;
    char *p62;
    char *p63;
    char *p64;
    char *p65;
    char *p66;
    char *p67;
    char *p68;
    char *p69;
    char *p70;
    char *p71;
    char *p72;
    char *p73;
    char *p74;
    char *p75;
    char *p76;
    char *p77;
    char *p78;
    char *p79;
    char *p80;
    char *p81;
    char *p82;
    char *p83;
    char *p84;
    char *p85;
    char *p86;
    char *p87;
    char *p88;
    char *p89;
    char *p90;
    char *p91;
    char *p92;
    char *p93;
    char *p94;
    char *p95;
    char *p96;
    char *p97;
    char *p98;
    char *p99;
    char *p100;

    fp = fopen("file.txt", "r");
    if (fp == NULL) {
        printf("Error opening file!\n");
        exit(1);
    }

    while (fgets(line, MAX_LINE_LENGTH, fp) != NULL) {
        lines[i] = malloc(strlen(line) + 1);
        strcpy(lines[i], line);
        i++;
    }

    linesNumber = i;

    for (j = 0; j < linesNumber; j++) {
        p = strtok(lines[j], " ");
        p1 = strtok(NULL, " ");
        p2 = strtok(NULL, " ");
        p3 = strtok(NULL, " ");
        p4 = strtok(NULL, " ");
        p5 = strtok(NULL, " ");
        p6 = strtok(NULL, " ");
        p7 = strtok(NULL, " ");
        p8 = strtok(NULL, " ");
        p9 = strtok(NULL, " ");
        p10 = strtok(NULL, " ");
        p11 = strtok(NULL, " ");
        p12 = strtok(NULL, " ");
        p13 = strtok(NULL, " ");
        p14 = strtok(NULL, " ");
        p15 = strtok(NULL, " ");
        p16 = strtok(NULL, " ");
        p17 = strtok(NULL, " ");
        p18 = strtok(NULL, " ");
        p19 = strtok(NULL, " ");
        p20 = strtok(NULL, " ");
        p21 = strtok(NULL, " ");
        p22 = strtok(NULL, " ");
        p23 = strtok(NULL, " ");
        p24 = strtok(NULL, " ");
        p25 = strtok(NULL, " ");
        p26 = strtok(NULL, " ");
        p27 = strtok(NULL, " ");
        p28 = strtok(NULL, " ");
        p29 = strtok(NULL, " ");
        p30 = strtok(NULL, " ");
        p31 = strtok(NULL, " ");
        p32 = strtok(NULL, " ");
        p33 = strtok(NULL, " ");
        p34 = strtok(NULL, " ");
        p35 = strtok(NULL, " ");
        p36 = strtok(NULL, " ");
        p37 = strtok(NULL, " ");
        p38 = strtok(NULL, " ");
        p39 = strtok(NULL, " ");
        p40 = strtok(NULL, " ");
        p41 = strtok(NULL, " ");
        p42 = strtok(NULL, " ");
        p43 = strtok(NULL, " ");
        p44 = strtok(NULL, " ");
        p45 = strtok(NULL, " ");
        p46 = strtok(NULL, " ");
        p47 = strtok(NULL, " ");
        p48 = strtok(NULL, " ");
        p49 = strtok(NULL, " ");
        p50 = strtok(NULL, " ");
        p51 = strtok(NULL, " ");
        p52 = strtok(NULL, " ");
        p53 = strtok(NULL, " ");
        p54 = strtok(NULL, " ");
        p55 = strtok(NULL, " ");
        p56 = strtok(NULL, " ");
        p57 = strtok(NULL, " ");
        p58 = strtok(NULL, " ");
        p59 = strtok(NULL, " ");
        p60 = strtok(NULL, " ");
        p61 = strtok(NULL, " ");
