import heapq
from collections import Counter
from collections import defaultdict
from collections import deque
from collections import OrderedDict
from functools import reduce
from bisect import bisect_left, bisect_right
from itertools import accumulate
from itertools import chain
from itertools import combinations
from itertools import combinations_with_replacement
from itertools import groupby
from itertools import permutations
from itertools import product
from itertools import combinations_with_replacement
from itertools import combinations
from itertools import permutations
from math import gcd
from fractions import Fraction
from math import floor
from math import ceil
from math import factorial
from math import sqrt
from copy import deepcopy
from operator import itemgetter, attrgetter
from functools import partial
from fractions import Fraction
from decimal import Decimal
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction
from fractions import gcd
from fractions import Fraction


def main():
    n = int(input())
    a = list(map(int, input().split()))
    dp = [1] * n
    dp2 = [1] * n
    for i in range(1, n):
        if a[i] > a[i - 1]:
            dp[i] = dp[i - 1] + 1
        if a[n - i - 1] > a[n - i]:
            dp2[n - i - 1] = dp2[n - i] + 1

    ans = 0
    for i in range(n):
        if i == 0:
            ans = max(ans, dp[i + 1])
        elif i == n - 1:
            ans = max(ans, dp2[i - 1])
        else:
            ans = max(ans, dp[i + 1] + dp2[i - 1] - 1)
    print(ans)


if __name__ == "__main__":
    main()
