

def solve(n, m, s, roads):
    # Write your code here
    pass


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    n = int(next(tokens))  # type: int
    m = int(next(tokens))  # type: int
    s = int(next(tokens))  # type: int
    roads = [None] * (m)  # type: "List[List[int]]" 
    for i in range(m):
        roads[i] = [int(next(tokens)) for _ in range(2)]
    result = solve(n, m, s, roads)
    if isinstance(result, Iterable) and not isinstance(result, str):
        result = '\n'.join([str(v) for v in result])
    print(result)

if __name__ == '__main__':
    main()