# -*- coding: utf-8 -*-

# Solution
def solve():
    N, M = map(int, input().split())
    A = list(map(int, input().split()))
    B = list(map(int, input().split()))
    C = list(map(int, input().split()))
    D = list(map(int, input().split()))
    E = list(map(int, input().split()))
    F = list(map(int, input().split()))
    G = list(map(int, input().split()))
    H = list(map(int, input().split()))
    I = list(map(int, input().split()))
    J = list(map(int, input().split()))
    K = list(map(int, input().split()))
    L = list(map(int, input().split()))
    M = list(map(int, input().split()))
    N = list(map(int, input().split()))
    O = list(map(int, input().split()))
    P = list(map(int, input().split()))
    Q = list(map(int, input().split()))
    R = list(map(int, input().split()))
    S = list(map(int, input().split()))
    T = list(map(int, input().split()))
    U = list(map(int, input().split()))
    V = list(map(int, input().split()))
    W = list(map(int, input().split()))
    X = list(map(int, input().split()))
    Y = list(map(int, input().split()))
    Z = list(map(int, input().split()))
    print(A)
    print(B)
    print(C)
    print(D)
    print(E)
    print(F)
    print(G)
    print(H)
    print(I)
    print(J)
    print(K)
    print(L)
    print(M)
    print(N)
    print(O)
    print(P)
    print(Q)
    print(R)
    print(S)
    print(T)
    print(U)
    print(V)
    print(W)
    print(X)
    print(Y)
    print(Z)

solve()
