n, m = map(int, input().split())
a = list(map(int, input().split()))
a.sort()
cups = 0
pages = 0
days = 0
while cups < n:
    pages += a[cups]
    days += 1
    cups += 1
    if pages >= m:
        break
    if cups < n:
        pages -= days - 1
if pages < m:
    days = -1
print(days)


#!/usr/bin/python3
# -*- coding: utf-8 -*-
import os
import re
import subprocess
import sys
import time
import urllib
import urllib.request
import requests
import json
import codecs
import datetime
import string
import random
import shutil
import operator
import argparse
import csv
import math
import itertools
import fileinput
import collections
import functools
import glob
import heapq
import bisect
import copy
import queue
import threading
import multiprocessing
import concurrent.futures
import xml.etree.ElementTree
import xml.dom.minidom
import xml.sax.saxutils
import html.entities
import html.parser
import xmlrpc.client
import xmlrpc.server
import socketserver
import http.server
import http.cookies
import http.client
import ftplib
import telnetlib
import poplib
import smtplib
import email.message
import email.parser
import email.policy
import email.utils
import imaplib
import imghdr
import mimetypes
import email.mime
import email.mime.application
import email.mime.audio
import email.mime.base
import email.mime.image
import email.mime.message
import email.mime.multipart
import email.mime.text
import base64
import binascii
import quopri
import uu
import hashlib
import hmac
import secrets
import json
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
import json.encoder
import json.scanner
import json.tool
import json.decoder
