import os
import re

import math
import itertools
import collections
import bisect
import heapq
import fractions
import random
import string
import copy
import time
import functools
import operator
import numpy
import scipy
import numpy.linalg
import scipy.linalg
import numpy.random
import scipy.random
import numpy.fft
import scipy.fft
import numpy.fft.fftpack
import scipy.fft.fftpack
import numpy.fft.helper
import scipy.fft.helper
import numpy.ma
import scipy.ma
import numpy.lib
import scipy.lib
import numpy.lib.stride_tricks
import scipy.lib.stride_tricks
import numpy.polynomial
import scipy.polynomial
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.hermite
import scipy.polynomial.hermite
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.hermite_e
import scipy.polynomial.hermite_e
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.hermite
import scipy.polynomial.hermite
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.hermite_e
import scipy.polynomial.hermite_e
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.hermite
import scipy.polynomial.hermite
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.hermite_e
import scipy.polynomial.hermite_e
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.hermite
import scipy.polynomial.hermite
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.hermite_e
import scipy.polynomial.hermite_e
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.hermite
import scipy.polynomial.hermite
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.hermite_e
import scipy.polynomial.hermite_e
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.hermite
import scipy.polynomial.hermite
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.hermite_e
import scipy.polynomial.hermite_e
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.polynomial
import scipy.polynomial.polynomial
import numpy.polynomial.chebyshev
import scipy.polynomial.chebyshev
import numpy.polynomial.legendre
import scipy.polynomial.legendre
import numpy.polynomial.hermite
import scipy.polynomial.hermite
import numpy.polynomial.laguerre
import scipy.polynomial.laguerre
import numpy.
import sys

def main():
    d, t, s = map(int, sys.stdin.readline().split())
    if d / s <= t:
        print("Yes")
    else:
        print("No")

if __name__ == '__main__':
    main()
