
def solve(s):
    """
    >>> solve("BBAABBBA")
    'BB'
    >>> solve("ABACABA")
    'AB'
    >>> solve("ZZZAA")
    'ZZ'

    >>> solve("AA")
    'AA'
    >>> solve("A")
    'A'
    >>> solve("")
    ''
    >>> solve("ABC")
    ''
    >>> solve("ABCA")
    ''
    >>> solve("ABCAB")
    ''
    >>> solve("ABCABC")
    ''
    >>> solve("ABCABCA")
    ''
    >>> solve("ABCABCAB")
    ''
    >>> solve("ABCABCABC")
    ''
    >>> solve("ABCABCABCA")
    ''
    >>> solve("ABCABCABCAB")
    ''
    >>> solve("ABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCAB")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC")
    ''
    >>> solve("ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCA")
    ''
    True
    >>> solve("ABACABA") == "AB"
    True
    >>> solve("ZZZAA") == "ZZ"
    True
    """
    counter = dict()
    for i in range(len(s) - 1):
        two_gram = s[i:i+2]
        counter[two_gram] = counter.get(two_gram, 0) + 1
    max_value = max(counter.values())
    for k, v in counter.items():
        if v == max_value:
            return k


if __name__ == "__main__":
    n = int(input())
    s = input()
    result = solve(s)
    print(result)
