
def main():
    # N = int(input())
    # A = list(map(int, input().split()))
    # B = list(map(int, input().split()))
    # C = list(map(int, input().split()))
    # D = list(map(int, input().split()))
    # E = list(map(int, input().split()))
    # F = list(map(int, input().split()))
    # G = list(map(int, input().split()))
    # H = list(map(int, input().split()))
    # I = list(map(int, input().split()))
    # J = list(map(int, input().split()))
    # K = list(map(int, input().split()))
    # L = list(map(int, input().split()))
    # M = list(map(int, input().split()))
    # N = list(map(int, input().split()))
    # O = list(map(int, input().split()))
    # P = list(map(int, input().split()))
    # Q = list(map(int, input().split()))
    # R = list(map(int, input().split()))
    # S = list(map(int, input().split()))
    # T = list(map(int, input().split()))
    # U = list(map(int, input().split()))
    # V = list(map(int, input().split()))
    # W = list(map(int, input().split()))
    # X = list(map(int, input().split()))
    # Y = list(map(int, input().split()))
    # Z = list(map(int, input().split()))

    # a = input()
    # b = input()
    # c = input()
    # d = input()
    # e = input()
    # f = input()
    # g = input()
    # h = input()
    # i = input()
    # j = input()
    # k = input()
    # l = input()
    # m = input()
    # n = input()
    # o = input()
    # p = input()
    # q = input()
    # r = input()
    # s = input()
    # t = input()
    # u = input()
    # v = input()
    # w = input()
    # x = input()
    # y = input()
    # z = input()
    
    # print(a)
    # print(b)
    # print(c)
    # print(d)
    # print(e)
    # print(f)
    # print(g)
    # print(h)
    # print(i)
    # print(j)
    # print(k)
    # print(l)
    # print(m)
    # print(n)
    # print(o)
    # print(p)
    # print(q)
    # print(r)
    # print(s)
    # print(t)
    # print(u)
    # print(v)
    # print(w)
    # print(x)
    # print(y)
    # print(z)
    pass


if __name__ == "__main__":
    main()
