
import collections
import bisect
import sys

def main():
    a = list(map(int,sys.stdin.readline().split()))
    b = list(map(int,sys.stdin.readline().split()))
    c = list(map(int,sys.stdin.readline().split()))
    d = list(map(int,sys.stdin.readline().split()))
    e = list(map(int,sys.stdin.readline().split()))
    f = list(map(int,sys.stdin.readline().split()))
    g = list(map(int,sys.stdin.readline().split()))
    h = list(map(int,sys.stdin.readline().split()))
    i = list(map(int,sys.stdin.readline().split()))
    j = list(map(int,sys.stdin.readline().split()))
    k = list(map(int,sys.stdin.readline().split()))
    l = list(map(int,sys.stdin.readline().split()))
    m = list(map(int,sys.stdin.readline().split()))
    n = list(map(int,sys.stdin.readline().split()))
    o = list(map(int,sys.stdin.readline().split()))
    p = list(map(int,sys.stdin.readline().split()))
    q = list(map(int,sys.stdin.readline().split()))
    r = list(map(int,sys.stdin.readline().split()))
    s = list(map(int,sys.stdin.readline().split()))
    t = list(map(int,sys.stdin.readline().split()))
    u = list(map(int,sys.stdin.readline().split()))
    v = list(map(int,sys.stdin.readline().split()))
    w = list(map(int,sys.stdin.readline().split()))
    x = list(map(int,sys.stdin.readline().split()))
    y = list(map(int,sys.stdin.readline().split()))
    z = list(map(int,sys.stdin.readline().split()))
    aa = list(map(int,sys.stdin.readline().split()))
    ab = list(map(int,sys.stdin.readline().split()))
    ac = list(map(int,sys.stdin.readline().split()))
    ad = list(map(int,sys.stdin.readline().split()))
    ae = list(map(int,sys.stdin.readline().split()))
    af = list(map(int,sys.stdin.readline().split()))
    ag = list(map(int,sys.stdin.readline().split()))
    ah = list(map(int,sys.stdin.readline().split()))
    ai = list(map(int,sys.stdin.readline().split()))
    aj = list(map(int,sys.stdin.readline().split()))
    ak = list(map(int,sys.stdin.readline().split()))
    al = list(map(int,sys.stdin.readline().split()))
    am = list(map(int,sys.stdin.readline().split()))
    an = list(map(int,sys.stdin.readline().split()))
    ao = list(map(int,sys.stdin.readline().split()))
    ap = list(map(int,sys.stdin.readline().split()))
    aq = list(map(int,sys.stdin.readline().split()))
    ar = list(map(int,sys.stdin.readline().split()))
    as_ = list(map(int,sys.stdin.readline().split()))
    at = list(map(int,sys.stdin.readline().split()))
    au = list(map(int,sys.stdin.readline().split()))
    av = list(map(int,sys.stdin.readline().split()))
    aw = list(map(int,sys.stdin.readline().split()))
    ax = list(map(int,sys.stdin.readline().split()))
    ay = list(map(int,sys.stdin.readline().split()))
    az = list(map(int,sys.stdin.readline().split()))
    ba = list(map(int,sys.stdin.readline().split()))
    bb = list(map(int,sys.stdin.readline().split()))
    bc = list(map(int,sys.stdin.readline().split()))
    bd = list(map(int,sys.stdin.readline().split()))
    be = list(map(int,sys.stdin.readline().split()))
    bf = list(map(int,sys.stdin.readline().split()))
    bg = list(map(int,sys.stdin.readline().split()))
    bh = list(map(int,sys.stdin.readline().split()))
    bi = list(map(int,sys.stdin.readline().split()))
    bj = list(map(int,sys.stdin.readline().split()))
    bk = list(map(int,sys.stdin.readline().split()))
    bl = list(map(int,sys.stdin.readline().split()))
    bm = list(map(int,sys.stdin.readline().split()))
    bn = list(map(int,sys.stdin.readline().split()))
    bo = list(map(int,sys.stdin.readline().split()))
    bp = list(map(int,sys.stdin.readline().split()))
    bq = list(map(int,sys.stdin.readline().split()))
    br = list(map(int,sys.stdin.readline().split()))
    bs = list(map(int,sys.stdin.readline().split()))
    bt = list(map(int,sys.stdin.readline().split()))
    bu = list(map(int,sys.stdin.readline().split()))
    bv = list(map(int,sys.stdin.readline().split()))
    bw = list(map(int,sys.stdin.readline().split()))
    bx = list(map(int,sys.stdin.readline().split()))
    by = list(map(int,sys.stdin.readline().split()))
    bz = list(map(int,sys.stdin.readline().split()))
    ca = list(map(int,sys.stdin.readline().split()))
    cb = list(map(int,sys.stdin.readline().split()))
    cc = list(map(int,sys.stdin.readline().split()))
    cd = list(map(int,sys.stdin.readline().split()))

if __name__ == "__main__":
    main()
